[project]
name = "cslrtools-fluentsigners50"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ikeda", email = "ikeda@lee-lab.org" }
]
requires-python = ">=3.11"
dependencies = [
    "argparse-class-namespace",
    "cslrtools",
    "parse>=1.20.2",
]

[project.scripts]
cslrtools-fluentsigners50 = "cslrtools_fluentsigners50.__main__:main"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.uv.sources]
cslrtools = { path = "../cslrtools", editable = true }
argparse-class-namespace = { git = "ssh://git@gitlab.lee-lab.org/ikeda/argparse-class-namespace.git" }
